/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.14
 * Generated at: 2019-01-05 07:37:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/view/home/login-success.jsp", Long.valueOf(1546663412000L));
    _jspx_dependants.put("/WEB-INF/view/home/footer.jsp", Long.valueOf(1546663378000L));
    _jspx_dependants.put("/WEB-INF/view/home/header.jsp", Long.valueOf(1546663401000L));
    _jspx_dependants.put("/WEB-INF/view/home/navi-bar.jsp", Long.valueOf(1546663429000L));
    _jspx_dependants.put("/WEB-INF/view/home/head.jsp", Long.valueOf(1546663388000L));
    _jspx_dependants.put("/WEB-INF/view/home/side-menu.jsp", Long.valueOf(1546663441000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"");
      out.print(application.getContextPath());
      out.write("/resources/css/style.css\" />\n");
      out.write("</head>");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t");

		System.out.println(" => 홈 메인 입장");
	
      out.write("\n");
      out.write("\t<table id=\"wrapper\">\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td colspan=\"2\">");
      out.write("\n");
      out.write("<div id=\"header\">\n");
      out.write("\t<h1>비트 쇼핑몰</h1>\n");
      out.write("</div>");
      out.write("\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td colspan=\"2\">");
      out.write("\n");
      out.write("<div id=\"navi-bar\">\n");
      out.write("\t<ul>\n");
      out.write("\t\t<li><a href=\"home.do\">홈</a></li>\n");
      out.write("\t\t<li><a href=\"member.do\">회원관리</a>\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li><a href=\"member.do\">회원가입</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"\">회원정보수정</a></li>\n");
      out.write("\t\t\t</ul></li>\n");
      out.write("\t\t<li><a href=\"account.do\">계좌관리</a></li>\n");
      out.write("\n");
      out.write("\t\t<li><a href=\"article.do\">게시판</a>\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li><a href=\"article.do\">글쓰기</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"\">게시판 목록</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"\">게시판 수정</a></li>\n");
      out.write("\t\t\t</ul></li>\n");
      out.write("\t\t<li><a href=\"admin.do\">관리자</a>\n");
      out.write("\t</ul>\n");
      out.write("</div>");
      out.write("\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr style=\"height: 300px\">\n");
      out.write("\t\t\t<td style=\"width: 30%\">");
      out.write("\n");
      out.write("<div id=\"side-menu\"></div>");
      out.write("\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t\t<td>\n");
      out.write("\t\t\t\t<div id=\"content\">\n");
      out.write("\t\t\t\t");

				String compo = request.getAttribute("compo").toString();
				 switch(compo){
					 case "login-success" :
						 
      out.write('\n');

	String name = request.getAttribute("name").toString();
	if(name.equals("test")){
		
      out.write("\n");
      out.write("\t\t ");
      out.print(name );
      out.write(" 님 환영합니다. \n");
      out.write("\t\t");

	}

 
						 break;
					
				 }
				
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr style=\"height: 100px;\">\n");
      out.write("\t\t\t<td colspan=\"2\">");
      out.write("\n");
      out.write("<div id=\"footer\">footer!</div>");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t</table>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
